// Claude Code hooks for the agent (.claude/settings.json). Git hooks catch what gets committed;
// these catch what the agent writes to files, before any commit (PD-19).
//
//   node scripts/claude-hooks.mjs pre-edit    — PreToolUse Write|Edit|MultiEdit: a secret in the text
//                                                or a hand edit of a generated file → block (exit 2)
//   node scripts/claude-hooks.mjs post-edit   — PostToolUse: after project.yml, remind about xcodegen
import { readFileSync } from "node:fs";
import { relative } from "node:path";
import { SECRET_PATTERNS } from "./check-secrets.mjs";

/** Generated by scripts; edit through the generator (AGENTS.md). */
export const GENERATED = [
  [/^BibleReaderApp\/BibleReader\.xcodeproj\//, "cd BibleReaderApp && xcodegen generate (from project.yml)"],
  [/^docs\/generated\//, "the DB schema generator"],
  [/^trace\/[^/]+\.json$/, "node scripts/check-traceability.mjs / check-trajectory.mjs"],
  [/^docs\/qa\/(traceability|trajectory)-report\.md$/, "node scripts/check-traceability.mjs / check-trajectory.mjs"],
];

/** The new text the tool will write to the file. */
export function writtenText(input) {
  if (typeof input.content === "string") return input.content;
  if (Array.isArray(input.edits)) return input.edits.map((edit) => edit.new_string ?? "").join("\n");
  return input.new_string ?? "";
}

/** The block reason or null. */
export function checkEdit(input, root) {
  const path = relative(root, input.file_path ?? "");
  const generated = GENERATED.find(([pattern]) => pattern.test(path));
  if (generated) return `${path} is generated: do not edit it by hand, run: ${generated[1]}.`;
  const hit = writtenText(input).split("\n").map((line) => SECRET_PATTERNS.find(([, pattern]) => pattern.test(line))).find(Boolean);
  if (hit) return `${path}: the text looks like ${hit[0]}. API keys belong only in the Keychain, not in project files.`;
  return null;
}

/** A reminder after an edit or null. */
export function afterEdit(input, root) {
  return relative(root, input.file_path ?? "") === "BibleReaderApp/project.yml"
    ? "project.yml changed: run `cd BibleReaderApp && xcodegen generate`, otherwise Xcode builds the old BibleReader.xcodeproj."
    : null;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const event = JSON.parse(readFileSync(0, "utf8"));
  const root = process.env.CLAUDE_PROJECT_DIR ?? event.cwd ?? process.cwd();
  const input = event.tool_input ?? {};
  if (process.argv[2] === "pre-edit") {
    const reason = checkEdit(input, root);
    if (reason) {
      console.error(reason);
      process.exit(2);
    }
  } else if (process.argv[2] === "post-edit") {
    const note = afterEdit(input, root);
    if (note) console.log(JSON.stringify({ hookSpecificOutput: { hookEventName: "PostToolUse", additionalContext: note } }));
  }
}
